const mongoose = require('mongoose')
const dashBoardSchema = new mongoose.Schema({
    date:{
        type:Date
    },
    totalCovidPatients:{
        type:Number
    },
    totalDeaths:{
        type:Number
    },
    totalActiveCases:{
        type:Number
    },
    deaths:[{
        count:{
            type:Number
        },
        createdAt:{
            type:Date,
            default:Date.now()
        },
        createdBy:{
            name:{
                type:String
            }
        }
    }],
    recovered:[{
        count:{
            type:Number
        },
        createdAt:{
            type:Date,
            default:Date.now()
        },
        createdBy:{
            name:{
                type:String
            }
        }
    }],
    cases:[{
        positive:{
            type:Number
        },
        negative:{
            type:Number
        },
        createdAt:{
            type:Date,
            default:Date.now()
        },
        createdBy:{
            name:{
                type:String
            }
        }
    }]
})

dashBoardSchema.pre('save',function(next){
    console.log(this)
    // console.log(this)
    next()
})
const DashBoard = mongoose.model('DashBoard',dashBoardSchema)
module.exports=DashBoard